# Cartesian linear/angular velocities (Gripper)
max_vx: 0.5 # m/s
max_vy: 0.5 # m/s
max_vz: 0.5 # m/s
max_wx: 1.0 # rad/s
max_wy: 1.0 # rad/s
max_wz: 1.0 # rad/s

# Cartesian linear/angular positions (Gripper)
max_dx: 0.3 # m
max_dy: 0.4 # m
max_dz: 0.4 # m
#max_dR: 3.0   # rad (~180 deg)
#max_dP: 2.0   # rad (~120 deg)
#max_dY: 3.0   # rad (~180 deg)
max_dR: 3.5   # rad (~180 deg)
max_dP: 2.5   # rad (~120 deg)
max_dY: 3.5   # rad (~180 deg)

# Sign for linear/angular velocities (Gripper)
sign_vx: -1.0
sign_vy: -1.0
sign_vz: 1.0
sign_wx: -1.0
sign_wy: 1.0
sign_wz: 1.0

# Input axes (Joystick)
axis_vx: 2
axis_vy: 0
axis_vz: 1
axis_wx: 0
axis_wy: 2
axis_wz: 1

# Input buttons (Joystick)
pos_button: 0
ang_button: 3
deadman_button: 2
gripper_button: 1

# Timeout for joystick reset (<0 no timeout)
joy_msg_timeout: -1
