#Publish all joint states
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 50

# Joint trajectory controller
position_trajectory_controller:
  type: "kuka_control/JointTrajectoryController"
  joints:
    - joint_a1
    - joint_a2
    - joint_a3
    - joint_a4
    - joint_a5
    - joint_a6

  gains:
    joint_a1: {p: 10, d: 1, i: 0.1}
    joint_a2: {p: 10, d: 1, i: 0.1}
    joint_a3: {p: 10, d: 1, i: 0.1}
    joint_a4: {p: 10, d: 1, i: 0.1}
    joint_a5: {p: 10, d: 1, i: 0.1}
    joint_a6: {p: 10, d: 1, i: 0.1}


  state_publish_rate: 50 # Defaults to 50
  action_monitor_rate: 20 # Defaults to 20
